spring.application.name=ProductService
server.port=8081
#----------------------------------- Database Starts-------------------------------#
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
#----------------------------------- Database Starts-------------------------------#
#----------------------------------- Spring Jpa Starts-------------------------------#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#----------------------------------- Spring Jpa Ends-------------------------------#

#----------------------------------- Keycloak Starts-------------------------------#
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL:http://localhost:9090/realms/EcommerceMs}
#----------------------------------- Keycloak Ends-------------------------------#

#----------------------------------- Logging Starts-------------------------------#
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.apache.kafka=DEBUG
#----------------------------------- Logging Ends Here------------------------------#
#-------------------------------->Resilience Starts here---------------------------------------#
#Resilence Retry property
retry.updateStockRetry.maxAttempts=2
retry.updateStockRetry.backoff.delay=2000

# =============================Circuit Breaker ============================================== #
resilience4j.circuitbreaker.instances.circuitBreakerService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.circuitBreakerService.sliding-window-size=5
resilience4j.circuitbreaker.instances.circuitBreakerService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.circuitBreakerService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.circuitBreakerService.slow-call-rate-threshold=50
resilience4j.circuitbreaker.instances.circuitBreakerService.slow-call-duration-threshold=5s
resilience4j.circuitbreaker.instances.circuitBreakerService.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.circuitBreakerService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.circuitBreakerService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.circuitBreakerService.max-wait-duration-in-half-open-state=0
resilience4j.circuitbreaker.instances.circuitBreakerService.record-exceptions=java.lang.RuntimeException
resilience4j.circuitbreaker.instances.circuitBreakerService.register-health-indicator=true
resilience4j.circuitbreaker.instances.circuitBreakerService.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.circuitBreakerService.writable-stack-trace-enabled=true
resilience4j.circuitbreaker.instances.circuitBreakerService.allow-health-indicator-to-fail=true
#------------------------------------------->Resilience End------------------------------------------#

#-------------------------------->Actuators Starts here---------------------------------------#
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always
#-------------------------------->Actuators Ends here---------------------------------------#

#----------------------------------- Grpc Starts-------------------------------#
grpc.server.port=7000
grpc.server.enable-reflection=true
#----------------------------------- Grpc Ends Here------------------------------#

##-------------------------------------Kafka Producer Starts here--------------------------------------------#
#spring.kafka.producer.bootstrap-servers=localhost:9094
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
##-------------------------------------Kafka Producer Ends here--------------------------------------------#
#
##-------------------------------------Kafka Consumer Starts here--------------------------------------------#
#spring.kafka.consumer.bootstrap-servers=localhost:9094
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
#spring.kafka.consumer.group-id=kafkaconsumerid
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.enable-auto-commit=true
#spring.kafka.consumer.auto-commit-interval=1000
##-------------------------------------Kafka Consumer Ends here--------------------------------------------#