spring.application.name=ApiGateWay
server.port=8084
#----------------------------------- Spring Cloud Gateway Starts-------------------------------#
#Product Service#
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/product/**
#Order Service#
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/order/**

logging.level.org.springframework.cloud.gateway=DEBUG
#----------------------------------- Spring Cloud Gateway Ends-------------------------------#

#----------------------------------- Actuator Starts------------------------------#
management.endpoints.web.exposure.include=gateway,health
management.endpoint.gateway.enabled=true
#----------------------------------- Actuator Ends-------------------------------#

#----------------------------------- Keycloak Starts-------------------------------#
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL:http://localhost:9090/realms/EcommerceMs}
spring.security.oauth2.client.provider.ecommerce-backend.token-uri=http://localhost:9090/realms/EcommerceMs/protocol/openid-connect/token
spring.security.oauth2.client.registration.ecommerce-backend.client-id=product-service
spring.security.oauth2.client.registration.ecommerce-backend.client-secret=D41hUpgE4tN2vC8BbHNoK6F5zrRL5JL3
spring.security.oauth2.client.registration.ecommerce-backend.authorization-grant-type=password
spring.security.oauth2.client.provider.ecommerce-backend.logout-uri=http://localhost:9090/realms/EcommerceMs/protocol/openid-connect/logout
#----------------------------------- Keycloak Ends-------------------------------#
