spring.application.name=PaymentService
server.port=8083
#----------------------------------- Database Starts-------------------------------#
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
#----------------------------------- Database Starts-------------------------------#
#----------------------------------- Spring Jpa Starts-------------------------------#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#----------------------------------- Spring Jpa Ends-------------------------------#
#----------------------------------- Grpc As Client Starts-------------------------------#
grpc.client.productInformation.address=static://localhost:7000
grpc.client.productInformation.negotiation-type=plaintext
grpc.client.orderInformation.address=static://localhost:7001
grpc.client.orderInformation.negotiation-type=plaintext
grpc.server.port=-1
#----------------------------------- Grpc As Client Starts------------------------------#
#----------------------------------- Keycloak Starts-------------------------------#
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL:http://localhost:9090/realms/EcommerceMs}
spring.security.oauth2.client.registration.ecommerce-backend.client-id=product-service
spring.security.oauth2.client.registration.ecommerce-backend.client-secret=D41hUpgE4tN2vC8BbHNoK6F5zrRL5JL3
spring.security.oauth2.client.registration.ecommerce-backend.authorization-grant-type=client_credentials
spring.security.oauth2.client.provider.ecommerce-backend.token-uri=http://localhost:9090/realms/EcommerceMs/protocol/openid-connect/token
#----------------------------------- Keycloak Ends-------------------------------#


#---------------------------------Kafka Producer Starts-----------------------------#
spring.kafka.producer.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#---------------------------------Kafka Producer starts-----------------------------#
