KafkaServer {
    org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
    oauth.token.endpoint.uri="http://keycloak:9090/realms/EcommerceMs/protocol/openid-connect/token"
    oauth.client.id="product-service"
    oauth.client.secret="D41hUpgE4tN2vC8BbHNoK6F5zrRL5JL3"
    oauth.jwks.endpoint.uri="http://keycloak:9090/realms/EcommerceMs/protocol/openid-connect/certs"
    oauth.expected.issuer="http://keycloak:9090/realms/EcommerceMs"
    oauth.scope="openid"
    ;
};

Client {
    org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
    oauth.token.endpoint.uri="http://keycloak:9090/realms/EcommerceMs/protocol/openid-connect/token"
    oauth.client.id="product-service"
    oauth.client.secret="D41hUpgE4tN2vC8BbHNoK6F5zrRL5JL3"
    oauth.jwks.endpoint.uri="http://keycloak:9090/realms/EcommerceMs/protocol/openid-connect/certs"
    oauth.expected.issuer="http://keycloak:9090/realms/EcommerceMs"
    oauth.scope="openid"
    ;
};